### ISSUE TITLE
Constructor from decimal truncates to 12 decimal places

### ISSUE THREAD

**Issue by NullQubit** [AdamWhiteHat/BigDecimal#66]
**Description**
So I spent a few hours tracking down where some inaccuracies were coming from and ended up at this:
`new BigDecimal(79193.074346525013163981460149m) `

Digging into it a bit deeper I noticed that the library uses ToString("G17") to parse the decimal as a string. G17 format should not be used for decimals as some accuracy is lost.

**Error/Exception Message**
When instantiating using the BigDecimal(decimal) constructor with the above value, the resulting BigDecimal truncates the value to 12 decimal places (17 total significant digits) Example:

`new BigDecimal(79193.074346525013163981460149m) + 0.0000000000009m`

Note: The truncation happens also when a cast (implicit or explicit) is performed to a decimal.

**Expected Behavior**
The result should be a BigDecimal with value 79193.074346525014063981460149

**Actual Behavior**
The resulting value is 79193.0743465250139 because after the constructor is called the value was truncated to 79193.074346525013

**Steps To Reproduce**
`Instantiate using the BigDecimal(decimal) constructor and pass a decimal with more than 17 significant digits`

**Comment by AdamWhiteHat** [comment]
Kay, that should be fixed.
I published a new NuGet version that includes this fix: [ExtendedNumerics.BigDecimal 3000.0.2.358](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/3000.0.2.358)

The main issue was I was funneling all type conversions through the string parsing function, which would be fine, except there was a known issue with .NET numeric string formatting where full precision and roundtripping between string formatting and parsing was not guaranteed, and it did not sound like Microsoft was intent on fixing it.
Fixing this required obtaining the Decimal value through numeric methods instead of relying upon consistent and correct string formatting from the framework.

**Comment by AdamWhiteHat** [comment]
Hopefully version [3000.0.2.358](https://www.nuget.org/packages/ExtendedNumerics.BigDecimal/3000.0.2.358) functions for you as expected. I took your example and added it as a test to the test project, and its passing. But the nature of the change should mean its applicable beyond just this particular case.

I'm closing this ticket now. Feel free to open another ticket if you are not satisfied that this issue is settles, or if you discover any other defects.

Thank you for bringing this issue to my attention. This library now has much more robust conversions from decimal value types now because of it.
